server.port=8090

spring.cloud.gateway.routes[0].id=cursos-route
spring.cloud.gateway.routes[0].uri=lb://examen-aplicaciones
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/cursos/**

spring.cloud.gateway.routes[1].id=profesores-route
spring.cloud.gateway.routes[1].uri=lb://examen-aplicaciones
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/profesores/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
